version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=niffler-api
      - RABBITMQ_DEFAULT_PASS=niffler-api
    networks:
      - rabbitmq_go_net

  mysql_dev:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=niffler-api
      - MYSQL_DATABASE=niffler-api
      - MYSQL_USER=niffler-api
      - MYSQL_PASSWORD=niffler-api
    expose:
      - '3306'
    ports:
      - '3306:3306'

networks:
  rabbitmq_go_net:
    driver: bridge