AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:


Resources:
  ProfileApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: br.com.santos.vinicius.nifflerapi.config.handler.LambdaHandler::handleRequest
      Runtime: java11
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          TWITCH_AUTH_BASE_URL: https://id.twitch.tv/oauth2/
          TWITCH_HELIX_BASE_URL: https://api.twitch.tv/helix/
          CLIENT_ID: YOUR_TWITCH_CLIENT_ID
          CLIENT_SECRET: YOUR_TWITCH_SECRET_ID
          AWS__ACCESS_KEY: YOUR_AWS_ACCESS_KEY
          AWS__SECRET_KEY: YOR_AWS_SECRET_KEY
      Events:
        Blacklist:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY