package br.com.santos.vinicius.nifflerapi.model.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;
import java.util.Objects;
import java.util.UUID;

@Setter
@Getter
@NoArgsConstructor
@DynamoDBTable(tableName = "blacklist")
public class BlacklistEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "username")
    private String username;

    @DynamoDBAttribute(attributeName = "user_id")
    private Long userId;

    @DynamoDBAttribute(attributeName = "created_at")
    private Date createdAt;

    public BlacklistEntity(String username, Long userId) {
        this.id = UUID.randomUUID().toString();
        this.userId = userId;
        this.createdAt = new Date();
        this.username = username;
    }

    public boolean equalsTwitchUser(Object obj) {
        if (obj == null) return false;
        if (obj == this) return true;
        return Objects.equals(this.username, ((UserEntity) obj).getUsername())
                && Objects.equals(this.userId, ((UserEntity) obj).getUserId());
    }

}
