package br.com.santos.vinicius.nifflerapi.model.entity;

import br.com.santos.vinicius.nifflerapi.constant.UserOriginEnum;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "user_auth")
public class UserAuthEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id = UUID.randomUUID().toString();

    @DynamoDBAttribute(attributeName = "user_name")
    private String userName;

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "origin")
    private UserOriginEnum origin;

}
