package br.com.santos.vinicius.nifflerapi.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

@Setter
@Getter
@NoArgsConstructor
@DynamoDBTable(tableName = "user_message")
public class UserMessageEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id = UUID.randomUUID().toString();

    @DynamoDBAttribute(attributeName = "user_id")
    private Long userId;

    @DynamoDBAttribute(attributeName = "message_length")
    private int messageLength;

    @DynamoDBAttribute(attributeName = "points_to_add")
    private BigDecimal pointsToAdd;

    @DynamoDBAttribute(attributeName = "is_spam")
    private boolean isSpam;

    @DynamoDBAttribute(attributeName = "created_at")
    private Date createdAt = new Date();

    public UserMessageEntity(Long userId, int messageLength, BigDecimal pointsToAdd, boolean isSpam) {
        this.userId = userId;
        this.messageLength = messageLength;
        this.pointsToAdd = pointsToAdd;
        this.isSpam = isSpam;
    }
}
