package br.com.santos.vinicius.nifflerapi.model.entity;

import br.com.santos.vinicius.nifflerapi.model.TwitchUserModelData;
import br.com.santos.vinicius.nifflerapi.model.dto.UserMessageDto;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;
import java.util.Objects;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "user")
public class UserEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id = UUID.randomUUID().toString();

    @DynamoDBAttribute(attributeName = "user_id")
    private Long userId;

    @DynamoDBAttribute(attributeName = "username")
    private String username;

    @DynamoDBAttribute(attributeName = "display_name")
    private String displayName;

    @DynamoDBAttribute(attributeName = "points_to_add")
    private Double pointsToAdd = 0.0;

    @DynamoDBAttribute(attributeName = "points_added")
    private Double pointsAdded = 0.0;

    @DynamoDBAttribute(attributeName = "created_at")
    private Date createdAt = new Date();

    public UserEntity(Long userId, String username, String displayName, Double pointsToAdd, Double pointsAdded) {
        this.userId = userId;
        this.username = username;
        this.displayName = displayName;
        this.pointsToAdd = pointsToAdd;
        this.pointsAdded = pointsAdded;
        this.createdAt = new Date();
    }

    public boolean equalsTwitchUser(Object obj) {
        if (obj == null) return false;
        if (obj == this) return true;
        return Objects.equals(this.username, ((TwitchUserModelData) obj).getLogin())
                && Objects.equals(this.displayName, ((TwitchUserModelData) obj).getDisplay_name());
    }

    public UserEntity fetchUserFromTwitchUser(Object obj) {
        if (this.equalsTwitchUser(obj)) return this;

        this.username = ((TwitchUserModelData) obj).getLogin();
        this.displayName = ((TwitchUserModelData) obj).getDisplay_name();

        return this;
    }

    public boolean equalsUserMessage(Object obj) {
        if (obj == null) return false;
        if (obj == this) return true;

        return Objects.equals(this.username, ((UserMessageDto) obj).getUsername())
                && Objects.equals(this.displayName, ((UserMessageDto) obj).getDisplayName());
    }

    public void fetchUserFromMessage(Object obj) {
        if (this.equalsUserMessage(obj)) return;

        this.username = ((UserMessageDto) obj).getUsername();
        this.displayName = ((UserMessageDto) obj).getDisplayName();
    }
}
