#Workflow name
name: CI/CD Pipeline Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build-deploy:
    name: Deploy application to lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - uses: aws-actions/setup-sam@v1
      - name: Install CLI
        uses: dopplerhq/cli-action@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS__ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS__SECRET_KEY}}
          aws-region: sa-east-1
      - name: Build with maven
        run: mvn -B package -DskipTests --file pom.xml
      # Setting up template.yaml with environment variables
      - name: Setup template-deploy.yaml
        run: |
          chmod +x ./deploy-template.sh
          ./deploy-template.sh > template.yaml
        shell: bash
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          TWITCH_AUTH_BASE_URL: ${{secrets.TWITCH_AUTH_BASE_URL}}
          TWITCH_HELIX_BASE_URL: ${{secrets.TWITCH_HELIX_BASE_URL}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          AWS__ACCESS_KEY: ${{secrets.AWS__ACCESS_KEY}}
          AWS__SECRET_KEY: ${{secrets.AWS__SECRET_KEY}}
          STAGE_URL: ${{secrets.STAGE_URL}}
          PROD_URL: ${{secrets.PROD_URL}}
      # sam build
      - run: pwd
      - run: ls
      - run: pwd ./template-deploy.yaml
      - run: pwd template.yaml
      - run: sam build --use-container
      - run: ls
      - run: ls .aws-sam
      - run: ls ./.aws-sam/build
      - run: ls ./.aws-sam/build/ProfileApiFunction
      - run: ls ./.aws-sam/build/ProfileApiFunction/br
      - run: ls ./.aws-sam/build/ProfileApiFunction/br/com/
      - run: ls ./.aws-sam/build/ProfileApiFunction/br/com/santos
      - run: ls ./.aws-sam/build/ProfileApiFunction/br/com/santos/vinicius/nifflerapi
      - run: ls ./.aws-sam/build/ProfileApiFunction/br/com/santos/vinicius/nifflerapi/config
      - run: ls ./.aws-sam/build/ProfileApiFunction/br/com/santos/vinicius/nifflerapi/config/handler
      # sam deploy
      - run: sam deploy
      - run: rm template-deploy.yaml